### ISSUE TITLE
Incorrect algorithm

### ISSUE THREAD

**Issue by osama-h-rana** [ButchMonkey/Cube-Helper#4]
Hi, it's me again.

I think the algorithm "d (L' U2 L U') (L' U L)" in "Corner in U-Layer With Cross-Color on U-Face" is also incorrect.

The correct algorithm is "d' (L' U2 L U') (L' U L)"

Regards.

**Comment by ButchMonkey** [comment]
Thanks,
As mentioned in another issue, I had issues with the cloud provider I use to build apps. This is now resolved and I will be pushing updates this week to patch algs.

This one is first on the list
